# Please Leave Your Notes Here
Rmd 2: Is the paper restricted to finite populations? if so then change title to
"a comparison of design-based and model-based approaches for finite population 
spatial data"

Rmd 76: finite population or not? if so, then "inferences about a finite population" 
and "all units in a finite population".  Much but not all of the literature assumes
finite populations for comparisons. My understanding is that restricting to finite
populations is what is intended for this paper.

Rmd 80: design-based vs model-based in spatial context. Incorporating spatial location
can be done at the design stage, i.e., selection of the sample units from the finite 
set of population units, or at the analysis stage, incorporating spatial information
for estimation.  Should this paragraph address this?

"We define spatial data...": Virtually all data is spatial. Is just a question for us
whether the spatial information is either incorporated into the selection of units or
into the statistical estimation.  Could redo sentence to be: "We define spatial data as
data that incorporates the specific locations of the population units into either the 
design or estimation process."

In general, not clear throughout the paragraph whether refer to process of site selection 
or estimation.

Rmd 90: Like the section as it focuses on whether statistical inference comes from
process of selecting the sites (design-based design and analysis) or realization of 
statistical process (model-based analysis of realizations). While not explicitly stated,
either analysis could be based on explicit use of spatial location or not at all. That is, 
while the examples are spatial in nature neither their site selection nor analysis needs
to be spatial.


Rmd 92: "independent random sampling (IRS), stratified random sampling, and cluster sampling." Replace by "simple random sampling, stratified random sample, and cluster
sampling, which we refer to as Independent Random Sampling (IRS) survey designs". My 
assumption is that all of these are interpreted as using srs. GRTS-based survey designs applies to equal probability designs, stratified designs and cluster designs as well. 
Just as any spatially-balanced-based design does as well.

"typically assumed" - always? drop typically or what am I missing?

Rmd 170: Before this section is it useful to have a section that lays out the general
site selection and general analysis options. Thinking about site selection as design-based IRS, design-based GRTS, Arbitrary set of sites, selection for model-based. Then general analysis options as design-based no spatial, design-based spatial, model-based. This four by three table would show that model-based analyses are possible for all selection options. Design-based options with no spatial info possible for IRS-based and GRTS-based. Design-based options with spatial info possible for GRTS-based. 

Then the focus of the paper is to compare WHAT? design-based GRTS site selection/design-based spatial analysis to IRS-based site selection/model-based FPBK?


